In [1]:
!pip install nanoid

Collecting nanoid
  Downloading nanoid-2.0.0-py3-none-any.whl.metadata (3.5 kB)
Downloading nanoid-2.0.0-py3-none-any.whl (5.8 kB)
Installing collected packages: nanoid
Successfully installed nanoid-2.0.0

In [12]:
import pandas as pd
import random
import numpy as np
import nanoid
import itertools
from datetime import datetime, timedelta

random.seed(42)

In [13]:
def generate_random_date(start_date, end_date):
    # Generate a random date between start_date and end_date
    delta = end_date - start_date
    random_days = random.randint(0, delta.days)
    random_date = start_date + timedelta(days=random_days)
    return random_date.strftime('%d/%m/%y')  # Format to 'DD/MM/YY'

In [29]:
data = {
    'MCC_GROUP': ['ALFAMART', 'INDOMARET', 'SUPERINDO', 'ERAFONE', 'IBOX', 'BARAYA', 'DAYTRANS', 'GRAPARI', 'GERAI IM3', 'IKEA', 'DECATHLON'],
    'MERCHANT_CATEGORY': ['Food & Beverage', 'Lifestyle', 'Travel & Transportation', 'Gadget & Electronics', 'E-Commerce', 'Health & Beauty', 'Others/Miscellaneous', 'Telco'],
    'ASSETS': list(range(1, 6)),
    'AGE': list(range(1, 6)),
    'SEGMENTATION': ['All Segment', 'Working Professionals', 'Emerging Wealth', 'Wealthy Achievers', 'Young Gen & Early Jobber', 'Mature High Networth', 'Silver Ager', 'Minimal'],
    'RELIGION': ['Islam', 'Christian', 'Catholic', 'Buddha', 'Hindu', 'Konghucu', 'Others'],
    'GENDER': ['M', 'F'],
    'LOCATION': ['Nasional', 'Balikpapan', 'Bandung', 'Denpasar', 'Jakarta', 'Makassar', 'Malang', 'Manado', 'Medan', 'Padang', 'Palembang', 'Papua', 'Semarang', 'Surabaya', 'Yogyakarta'],
    'TIME': ['WEEKDAY - WORKING TIME', 'WEEKDAY - RESTING TIME', 'WEEKDAY - TRAVELING TIME', 'WEEKEND - WEEKEND'],
    'RANKING': list(range(1,11))
}

In [80]:
# Generate all combinations of list1 and list2
combinations = list(itertools.product(data['MCC_GROUP'], data['MERCHANT_CATEGORY']))

master_merchant = pd.DataFrame(combinations, columns=['MCC_GROUP', 'MERCHANT_CATEGORY'])
n = len(master_merchant)
times = datetime.now().strftime('%Y-%m-%d %H:%M:%S %z')
times
other = {
    'ID': [str(nanoid.generate(size=21)) for _ in range(n)],
    'UPDATE_BY': ['Camdun' for _ in range(n)],
    'UPDATED_TIME': [times for _ in range(n)],
    'CREATED_BY': ['Camdun' for _ in range(n)],
    'CREATED_TIME': [times for _ in range(n)]
}

for key, val in other.items():
    master_merchant[key] = other[key]

master_merchant = master_merchant[['ID', 'MCC_GROUP', 'MERCHANT_CATEGORY', 'UPDATE_BY', 'UPDATED_TIME', 'CREATED_BY', 'CREATED_TIME']]
master_merchant

,ID,MCC_GROUP,MERCHANT_CATEGORY,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,hQO3XryVg9w7lplANny20,ALFAMART,Food & Beverage,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
1,CGEG1rrW0Q6MqnSE5OjDn,ALFAMART,Lifestyle,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
2,zrpe3ndcqRzkYYs8OfywX,ALFAMART,Travel & Transportation,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
3,d-GSi8MyiJvC_QKVSCwGZ,ALFAMART,Gadget & Electronics,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
4,Pv5WgUMe5QR80GtRVvXRJ,ALFAMART,E-Commerce,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
...,...,...,...,...,...,...,...
83,34eC7CuxHXfFJkzklwv9k,DECATHLON,Gadget & Electronics,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
84,P-oVPwyR5u-QDXCUuHRB4,DECATHLON,E-Commerce,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
85,3NYyjqfYz7c3Hx-8dmuUj,DECATHLON,Health & Beauty,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
86,3kHQyPkoM678Oal3096PO,DECATHLON,Others/Miscellaneous,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32
87,1DS-E41YKCT65Q-HkRH7n,DECATHLON,Telco,Camdun,2024-10-25 21:48:32,Camdun,2024-10-25 21:48:32

In [10]:
master_user_columns = ['ID','USER_ID','GENDER','RELIGION','TOTAL_ASSETS','ACCOUNT_AGE','TRANSACTION_TIME','SEGMENTATION','UPDATE_BY','UPDATED_TIME','CREATED_BY','CREATED_TIME']
n = 1000
master_user = pd.DataFrame({
    'ID'                : [str(nanoid.generate(size=21)) for _ in range(n)],
    'USER_ID'           : [f'USER_{i:04}' for i in range(n)],
    'GENDER'            : [random.choice(data['GENDER']) for _ in range(n)],
    'RELIGION'          : [random.choice(data['RELIGION']) for _ in range(n)],
    'TOTAL_ASSETS'      : [random.choice(data['ASSETS']) for _ in range(n)],
    'ACCOUNT_AGE'       : [random.choice(data['AGE']) for _ in range(n)],
    'TRANSACTION_TIME'  : [random.choice(data['TIME']) for _ in range(n)],
    'SEGMENTATION'      : [random.choice(data['SEGMENTATION']) for _ in range(n)],
    'UPDATE_BY'         : ['Camdun' for _ in range(n)],
    'UPDATED_TIME'      : [datetime.now().strftime('%H:%M:%S') for _ in range(n)],
    'CREATED_BY'        : ['Camdun' for _ in range(n)],
    'CREATED_TIME'      : [datetime.now().strftime('%H:%M:%S') for _ in range(n)]
})

master_user

,ID,USER_ID,GENDER,RELIGION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,SEGMENTATION,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,6FCT6AtPkGDDmZFDFNh3-,USER_0000,M,Islam,5,5,WEEKDAY - RESTING TIME,Minimal,Camdun,19:46:07,Camdun,19:46:07
1,mnzFZFoC8UtMZQwZ7p8-7,USER_0001,M,Konghucu,1,2,WEEKDAY - WORKING TIME,Silver Ager,Camdun,19:46:07,Camdun,19:46:07
2,ADO0Z9xqfDb_cozpvw-ZO,USER_0002,F,Christian,2,3,WEEKDAY - RESTING TIME,Wealthy Achievers,Camdun,19:46:07,Camdun,19:46:07
3,rS3cddAF_Z24FXk_JXgEf,USER_0003,M,Konghucu,3,5,WEEKDAY - WORKING TIME,Silver Ager,Camdun,19:46:07,Camdun,19:46:07
4,dM_4KuNqMLRHV_tcx3J30,USER_0004,M,Konghucu,1,4,WEEKEND - WEEKEND,Mature High Networth,Camdun,19:46:07,Camdun,19:46:07
...,...,...,...,...,...,...,...,...,...,...,...,...
995,-IAouet_U5vhtRVKrX6D6,USER_0995,F,Buddha,1,5,WEEKDAY - TRAVELING TIME,Working Professionals,Camdun,19:46:07,Camdun,19:46:07
996,clILPCyOE3VdEA2y_CICB,USER_0996,F,Hindu,2,5,WEEKEND - WEEKEND,Minimal,Camdun,19:46:07,Camdun,19:46:07
997,PWKWNtYBKi8OfGXqlRLnY,USER_0997,M,Buddha,2,1,WEEKDAY - TRAVELING TIME,Mature High Networth,Camdun,19:46:07,Camdun,19:46:07
998,e80dha23rP0i14SE95nS3,USER_0998,M,Others,5,2,WEEKDAY - TRAVELING TIME,Working Professionals,Camdun,19:46:07,Camdun,19:46:07
999,UJL9WLwliYHb0dfJt0HIN,USER_0999,F,Buddha,2,2,WEEKDAY - RESTING TIME,Minimal,Camdun,19:46:07,Camdun,19:46:07

In [14]:
n = 10000
master_promo_1 = pd.DataFrame({
    'ID'                : [str(nanoid.generate(size=21)) for _ in range(n)],
    'PROMO_ID'          : [f'PROMO_{i:05}' for i in range(n)],
    'MCC_GROUP'         : [random.choice(data['MCC_GROUP']) for _ in range(n)],
    'MERCHANT_CATEGORY' : [random.choice(data['MERCHANT_CATEGORY']) for _ in range(n)],
    'RELIGION'          : [random.choice(data['RELIGION']) for _ in range(n)],
    'GENDER'            : [random.choice(data['GENDER']) for _ in range(n)],
    'SEGMENTATION'      : [random.choice(data['SEGMENTATION']) for _ in range(n)],
    'TOTAL_ASSETS'      : [random.choice(data['ASSETS']) for _ in range(n)],
    'ACCOUNT_AGE'       : [random.choice(data['AGE']) for _ in range(n)],
    'TRANSACTION_TIME'  : [random.choice(data['TIME']) for _ in range(n)],
    'START_DATE'        : [generate_random_date(datetime.strptime('01/11/2024', '%d/%m/%Y'), datetime.strptime('30/06/2025', '%d/%m/%Y')) for _ in range(n)],
    'END_DATE'          : [generate_random_date(datetime.strptime('31/07/2025', '%d/%m/%Y'), datetime.strptime('31/12/2025', '%d/%m/%Y')) for _ in range(n)],
    'UPDATE_BY'         : ['Camdun' for _ in range(n)],
    'UPDATED_TIME'      : [datetime.now().strftime('%H:%M:%S') for _ in range(n)],
    'CREATED_BY'        : ['Camdun' for _ in range(n)],
    'CREATED_TIME'      : [datetime.now().strftime('%H:%M:%S') for _ in range(n)]
})

master_promo_1

,ID,PROMO_ID,MCC_GROUP,MERCHANT_CATEGORY,RELIGION,GENDER,SEGMENTATION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,START_DATE,END_DATE,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,Q-n1icBaHCUX5NXlkLO00,PROMO_00000,DECATHLON,Travel & Transportation,Catholic,F,Emerging Wealth,2,4,WEEKDAY - TRAVELING TIME,24/05/25,05/12/25,Camdun,19:56:05,Camdun,19:56:05
1,BtHw4asvBBm2fOaVyUm0y,PROMO_00001,INDOMARET,Food & Beverage,Others,M,Mature High Networth,1,1,WEEKDAY - WORKING TIME,23/01/25,27/12/25,Camdun,19:56:05,Camdun,19:56:05
2,xSoS4137NHOwF2JA35Q6P,PROMO_00002,ALFAMART,Lifestyle,Islam,F,Silver Ager,4,4,WEEKEND - WEEKEND,04/03/25,27/11/25,Camdun,19:56:05,Camdun,19:56:05
3,h-9Oc_jumOAF9IWuzkGQi,PROMO_00003,IBOX,Telco,Konghucu,M,Minimal,1,5,WEEKEND - WEEKEND,18/01/25,16/09/25,Camdun,19:56:05,Camdun,19:56:05
4,PmArVOFg6iHLFqOVIRg_m,PROMO_00004,ERAFONE,Health & Beauty,Islam,M,Emerging Wealth,1,5,WEEKDAY - RESTING TIME,13/03/25,22/11/25,Camdun,19:56:05,Camdun,19:56:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,mnuzmq2Cts5By13t_QSY6,PROMO_09995,BARAYA,Travel & Transportation,Islam,F,Emerging Wealth,1,3,WEEKDAY - RESTING TIME,28/05/25,13/12/25,Camdun,19:56:05,Camdun,19:56:05
9996,JlEnaRsH0mhTEKIEaYoJK,PROMO_09996,DAYTRANS,Telco,Konghucu,M,Young Gen & Early Jobber,5,5,WEEKDAY - RESTING TIME,18/12/24,29/10/25,Camdun,19:56:05,Camdun,19:56:05
9997,kffOoC5vYDk22YddNtYrn,PROMO_09997,IKEA,Travel & Transportation,Catholic,F,All Segment,5,1,WEEKDAY - TRAVELING TIME,18/01/25,03/11/25,Camdun,19:56:05,Camdun,19:56:05
9998,IZk0dqU0LVEAkENRT8LRX,PROMO_09998,BARAYA,E-Commerce,Catholic,F,Mature High Networth,5,3,WEEKDAY - WORKING TIME,26/01/25,13/08/25,Camdun,19:56:05,Camdun,19:56:05
9999,TIWsHCrk3dqIS6pwEpWXf,PROMO_09999,DAYTRANS,Health & Beauty,Christian,M,Mature High Networth,2,4,WEEKDAY - RESTING TIME,07/05/25,17/10/25,Camdun,19:56:05,Camdun,19:56:05

In [86]:
list_col = ['ID',
 'PROMO_ID',
 'MCC_GROUP',
 'MERCHANT_CATEGORY',
 'RELIGION',
 'GENDER',
 'SEGMENTATION',
 'PROMO_LOCATION',
 'TOTAL_ASSETS',
 'ACCOUNT_AGE',
 'TRANSACTION_TIME',
 'START_DATE',
 'END_DATE',
 'UPDATE_BY',
 'UPDATED_TIME',
 'CREATED_BY',
 'CREATED_TIME']

In [87]:
n = 10000
master_promo_2 = master_promo_1.copy()
master_promo_2['PROMO_LOCATION'] = [random.choice(data['LOCATION']) for _ in range(n)]
master_promo_2 = master_promo_2[list_col]

master_promo_2

,ID,PROMO_ID,MCC_GROUP,MERCHANT_CATEGORY,RELIGION,GENDER,SEGMENTATION,PROMO_LOCATION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,START_DATE,END_DATE,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,Q-n1icBaHCUX5NXlkLO00,PROMO_00000,DECATHLON,Travel & Transportation,Catholic,F,Emerging Wealth,Jakarta,2,4,WEEKDAY - TRAVELING TIME,24/05/25,05/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
1,BtHw4asvBBm2fOaVyUm0y,PROMO_00001,INDOMARET,Food & Beverage,Others,M,Mature High Networth,Makassar,1,1,WEEKDAY - WORKING TIME,23/01/25,27/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
2,xSoS4137NHOwF2JA35Q6P,PROMO_00002,ALFAMART,Lifestyle,Islam,F,Silver Ager,Malang,4,4,WEEKEND - WEEKEND,04/03/25,27/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
3,h-9Oc_jumOAF9IWuzkGQi,PROMO_00003,IBOX,Telco,Konghucu,M,Minimal,Makassar,1,5,WEEKEND - WEEKEND,18/01/25,16/09/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
4,PmArVOFg6iHLFqOVIRg_m,PROMO_00004,ERAFONE,Health & Beauty,Islam,M,Emerging Wealth,Padang,1,5,WEEKDAY - RESTING TIME,13/03/25,22/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,mnuzmq2Cts5By13t_QSY6,PROMO_09995,BARAYA,Travel & Transportation,Islam,F,Emerging Wealth,Manado,1,3,WEEKDAY - RESTING TIME,28/05/25,13/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9996,JlEnaRsH0mhTEKIEaYoJK,PROMO_09996,DAYTRANS,Telco,Konghucu,M,Young Gen & Early Jobber,Medan,5,5,WEEKDAY - RESTING TIME,18/12/24,29/10/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9997,kffOoC5vYDk22YddNtYrn,PROMO_09997,IKEA,Travel & Transportation,Catholic,F,All Segment,Makassar,5,1,WEEKDAY - TRAVELING TIME,18/01/25,03/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9998,IZk0dqU0LVEAkENRT8LRX,PROMO_09998,BARAYA,E-Commerce,Catholic,F,Mature High Networth,Papua,5,3,WEEKDAY - WORKING TIME,26/01/25,13/08/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9999,TIWsHCrk3dqIS6pwEpWXf,PROMO_09999,DAYTRANS,Health & Beauty,Christian,M,Mature High Networth,Jakarta,2,4,WEEKDAY - RESTING TIME,07/05/25,17/10/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06

In [33]:
n = int(5e6)
# time = datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
transaction_dma = pd.DataFrame({
    'ID'                : [str(nanoid.generate(size=21)) for _ in range(n)],
    'USER_ID'           : [random.choice(master_user['USER_ID']) for _ in range(n)],
    'MCC_GROUP'         : [random.choice(data['MCC_GROUP']) for _ in range(n)],
    'MERCHANT_CATEGORY' : [random.choice(data['MERCHANT_CATEGORY']) for _ in range(n)],
    'RANKING'           : [random.choice(data['RANKING']) for _ in range(n)],
    'UPDATE_BY'         : ['Camdun' for _ in range(n)],
    'UPDATED_TIME'      : [datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f') for _ in range(n)],
    'CREATED_BY'        : ['Camdun' for _ in range(n)],
    'CREATED_TIME'      : [datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f') for _ in range(n)]
})

transaction_dma

,ID,USER_ID,MCC_GROUP,MERCHANT_CATEGORY,RANKING,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,hVPqvJbCyey59XAFKTg6Q,USER_0579,IBOX,Others/Miscellaneous,3,Camdun,20:14:52,Camdun,20:15:37
1,h-_cJmammhsp9ALw79Rg5,USER_0252,DAYTRANS,E-Commerce,7,Camdun,20:14:52,Camdun,20:15:37
2,Wsfhn0VVvXLghJONDo5Jg,USER_0383,GRAPARI,Health & Beauty,4,Camdun,20:14:52,Camdun,20:15:37
3,XdikvOvdauyPrJB8AlQwL,USER_0508,SUPERINDO,Health & Beauty,10,Camdun,20:14:52,Camdun,20:15:37
4,WELCd0VvyYI8n7l9fZc4Y,USER_0292,GERAI IM3,Others/Miscellaneous,3,Camdun,20:14:52,Camdun,20:15:37
...,...,...,...,...,...,...,...,...,...
4999995,O6cLj5lr5koo_o2xQxb7o,USER_0913,DAYTRANS,Gadget & Electronics,2,Camdun,20:15:37,Camdun,20:16:27
4999996,o9520lJFHSIy_RmViT7z8,USER_0233,BARAYA,Telco,9,Camdun,20:15:37,Camdun,20:16:27
4999997,DQ6ofPr3JH6TciNEpSvec,USER_0349,INDOMARET,Lifestyle,6,Camdun,20:15:37,Camdun,20:16:27
4999998,b8yBotgQvdsV9bnZ3atTw,USER_0362,GERAI IM3,Gadget & Electronics,9,Camdun,20:15:37,Camdun,20:16:27
4999999,Np1SJPBJNKS87c4AgNchf,USER_0668,IKEA,Food & Beverage,3,Camdun,20:15:37,Camdun,20:16:27

In [42]:
master_promo_1.columns

Index(['ID', 'PROMO_ID', 'MCC_GROUP', 'MERCHANT_CATEGORY', 'RELIGION',
       'GENDER', 'SEGMENTATION', 'TOTAL_ASSETS', 'ACCOUNT_AGE',
       'TRANSACTION_TIME', 'START_DATE', 'END_DATE', 'UPDATE_BY',
       'UPDATED_TIME', 'CREATED_BY', 'CREATED_TIME'],
      dtype='object')

In [44]:
master_promo_1.shape

(10000, 16)

In [71]:
times = datetime.now().strftime('%Y-%m-%d %H:%M:%S %z')
times

'2024-10-25 21:41:06 '

In [72]:
time_user = [times for _ in range(len(master_user))]
master_user['CREATED_TIME'] = time_user
master_user['UPDATED_TIME'] = time_user

time_merchant = [times for _ in range(len(master_merchant))]
master_merchant['CREATED_TIME'] = time_merchant
master_merchant['UPDATED_TIME'] = time_merchant

time_promo_1 = [times for _ in range(len(master_promo_1))]
master_promo_1['CREATED_TIME'] = time_promo_1
master_promo_1['UPDATED_TIME'] = time_promo_1

master_promo_2['CREATED_TIME'] = time_promo_1
master_promo_2['UPDATED_TIME'] = time_promo_1

time_dma = [times for _ in range(len(transaction_dma))]
transaction_dma['CREATED_TIME'] = time_dma
transaction_dma['UPDATED_TIME'] = time_dma

In [73]:
master_user

,ID,USER_ID,GENDER,RELIGION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,SEGMENTATION,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,6FCT6AtPkGDDmZFDFNh3-,USER_0000,M,Islam,5,5,WEEKDAY - RESTING TIME,Minimal,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
1,mnzFZFoC8UtMZQwZ7p8-7,USER_0001,M,Konghucu,1,2,WEEKDAY - WORKING TIME,Silver Ager,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
2,ADO0Z9xqfDb_cozpvw-ZO,USER_0002,F,Christian,2,3,WEEKDAY - RESTING TIME,Wealthy Achievers,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
3,rS3cddAF_Z24FXk_JXgEf,USER_0003,M,Konghucu,3,5,WEEKDAY - WORKING TIME,Silver Ager,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
4,dM_4KuNqMLRHV_tcx3J30,USER_0004,M,Konghucu,1,4,WEEKEND - WEEKEND,Mature High Networth,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
...,...,...,...,...,...,...,...,...,...,...,...,...
995,-IAouet_U5vhtRVKrX6D6,USER_0995,F,Buddha,1,5,WEEKDAY - TRAVELING TIME,Working Professionals,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
996,clILPCyOE3VdEA2y_CICB,USER_0996,F,Hindu,2,5,WEEKEND - WEEKEND,Minimal,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
997,PWKWNtYBKi8OfGXqlRLnY,USER_0997,M,Buddha,2,1,WEEKDAY - TRAVELING TIME,Mature High Networth,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
998,e80dha23rP0i14SE95nS3,USER_0998,M,Others,5,2,WEEKDAY - TRAVELING TIME,Working Professionals,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
999,UJL9WLwliYHb0dfJt0HIN,USER_0999,F,Buddha,2,2,WEEKDAY - RESTING TIME,Minimal,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06

In [74]:
master_merchant

,ID,MCC_GROUP,MERCHANT_CATEGORY,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,ALFAMART,Food & Beverage,xKNYKdL1iVqeU7PLMJ0Se,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
1,ALFAMART,Lifestyle,Om-PC1HOUVZET2N2V_pf6,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
2,ALFAMART,Travel & Transportation,MZP2bGpIqg1ejtCNgZwgJ,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
3,ALFAMART,Gadget & Electronics,VHhEtvrM1oCyrhfDI6NlS,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
4,ALFAMART,E-Commerce,LO-pwEXEDTb_UStD6HWjz,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
...,...,...,...,...,...,...,...
83,DECATHLON,Gadget & Electronics,7rdwCy92F2rYP8rNCECob,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
84,DECATHLON,E-Commerce,UaH7Y0OPuAEYa8cWpBGDx,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
85,DECATHLON,Health & Beauty,01lh8aWVT7pFYPuRPHufU,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
86,DECATHLON,Others/Miscellaneous,JXdT6xsjO4S0CCpqVHYrP,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
87,DECATHLON,Telco,uUsgVKdGKcn3TMcv-aV3k,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06

In [75]:
master_promo_1

,ID,PROMO_ID,MCC_GROUP,MERCHANT_CATEGORY,RELIGION,GENDER,SEGMENTATION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,START_DATE,END_DATE,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,Q-n1icBaHCUX5NXlkLO00,PROMO_00000,DECATHLON,Travel & Transportation,Catholic,F,Emerging Wealth,2,4,WEEKDAY - TRAVELING TIME,24/05/25,05/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
1,BtHw4asvBBm2fOaVyUm0y,PROMO_00001,INDOMARET,Food & Beverage,Others,M,Mature High Networth,1,1,WEEKDAY - WORKING TIME,23/01/25,27/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
2,xSoS4137NHOwF2JA35Q6P,PROMO_00002,ALFAMART,Lifestyle,Islam,F,Silver Ager,4,4,WEEKEND - WEEKEND,04/03/25,27/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
3,h-9Oc_jumOAF9IWuzkGQi,PROMO_00003,IBOX,Telco,Konghucu,M,Minimal,1,5,WEEKEND - WEEKEND,18/01/25,16/09/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
4,PmArVOFg6iHLFqOVIRg_m,PROMO_00004,ERAFONE,Health & Beauty,Islam,M,Emerging Wealth,1,5,WEEKDAY - RESTING TIME,13/03/25,22/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,mnuzmq2Cts5By13t_QSY6,PROMO_09995,BARAYA,Travel & Transportation,Islam,F,Emerging Wealth,1,3,WEEKDAY - RESTING TIME,28/05/25,13/12/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9996,JlEnaRsH0mhTEKIEaYoJK,PROMO_09996,DAYTRANS,Telco,Konghucu,M,Young Gen & Early Jobber,5,5,WEEKDAY - RESTING TIME,18/12/24,29/10/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9997,kffOoC5vYDk22YddNtYrn,PROMO_09997,IKEA,Travel & Transportation,Catholic,F,All Segment,5,1,WEEKDAY - TRAVELING TIME,18/01/25,03/11/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9998,IZk0dqU0LVEAkENRT8LRX,PROMO_09998,BARAYA,E-Commerce,Catholic,F,Mature High Networth,5,3,WEEKDAY - WORKING TIME,26/01/25,13/08/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
9999,TIWsHCrk3dqIS6pwEpWXf,PROMO_09999,DAYTRANS,Health & Beauty,Christian,M,Mature High Networth,2,4,WEEKDAY - RESTING TIME,07/05/25,17/10/25,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06

In [76]:
master_promo_2

,ID,PROMO_ID,MCC_GROUP,MERCHANT_CATEGORY,RELIGION,GENDER,SEGMENTATION,PROMO_LOCATION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,START_DATE,END_DATE,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,Q-n1icBaHCUX5NXlkLO00,PROMO_00000,DECATHLON,Travel & Transportation,Catholic,F,Emerging Wealth,2,4,WEEKDAY - TRAVELING TIME,24/05/25,05/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
1,BtHw4asvBBm2fOaVyUm0y,PROMO_00001,INDOMARET,Food & Beverage,Others,M,Mature High Networth,1,1,WEEKDAY - WORKING TIME,23/01/25,27/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
2,xSoS4137NHOwF2JA35Q6P,PROMO_00002,ALFAMART,Lifestyle,Islam,F,Silver Ager,4,4,WEEKEND - WEEKEND,04/03/25,27/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
3,h-9Oc_jumOAF9IWuzkGQi,PROMO_00003,IBOX,Telco,Konghucu,M,Minimal,1,5,WEEKEND - WEEKEND,18/01/25,16/09/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
4,PmArVOFg6iHLFqOVIRg_m,PROMO_00004,ERAFONE,Health & Beauty,Islam,M,Emerging Wealth,1,5,WEEKDAY - RESTING TIME,13/03/25,22/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,mnuzmq2Cts5By13t_QSY6,PROMO_09995,BARAYA,Travel & Transportation,Islam,F,Emerging Wealth,1,3,WEEKDAY - RESTING TIME,28/05/25,13/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9996,JlEnaRsH0mhTEKIEaYoJK,PROMO_09996,DAYTRANS,Telco,Konghucu,M,Young Gen & Early Jobber,5,5,WEEKDAY - RESTING TIME,18/12/24,29/10/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9997,kffOoC5vYDk22YddNtYrn,PROMO_09997,IKEA,Travel & Transportation,Catholic,F,All Segment,5,1,WEEKDAY - TRAVELING TIME,18/01/25,03/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9998,IZk0dqU0LVEAkENRT8LRX,PROMO_09998,BARAYA,E-Commerce,Catholic,F,Mature High Networth,5,3,WEEKDAY - WORKING TIME,26/01/25,13/08/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9999,TIWsHCrk3dqIS6pwEpWXf,PROMO_09999,DAYTRANS,Health & Beauty,Christian,M,Mature High Networth,2,4,WEEKDAY - RESTING TIME,07/05/25,17/10/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06

In [77]:
# location = [random.choice(data['LOCATION']) for _ in range(int(5e6))]
# transaction_dma['PROMO_LOCATION'] = location

transaction_dma

,ID,USER_ID,MCC_GROUP,MERCHANT_CATEGORY,RANKING,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME,PROMO_LOCATION
0,hVPqvJbCyey59XAFKTg6Q,USER_0579,IBOX,Others/Miscellaneous,3,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Bandung
1,h-_cJmammhsp9ALw79Rg5,USER_0252,DAYTRANS,E-Commerce,7,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Makassar
2,Wsfhn0VVvXLghJONDo5Jg,USER_0383,GRAPARI,Health & Beauty,4,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Papua
3,XdikvOvdauyPrJB8AlQwL,USER_0508,SUPERINDO,Health & Beauty,10,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Semarang
4,WELCd0VvyYI8n7l9fZc4Y,USER_0292,GERAI IM3,Others/Miscellaneous,3,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Medan
...,...,...,...,...,...,...,...,...,...,...
4999995,O6cLj5lr5koo_o2xQxb7o,USER_0913,DAYTRANS,Gadget & Electronics,2,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Malang
4999996,o9520lJFHSIy_RmViT7z8,USER_0233,BARAYA,Telco,9,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Papua
4999997,DQ6ofPr3JH6TciNEpSvec,USER_0349,INDOMARET,Lifestyle,6,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Makassar
4999998,b8yBotgQvdsV9bnZ3atTw,USER_0362,GERAI IM3,Gadget & Electronics,9,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Bandung
4999999,Np1SJPBJNKS87c4AgNchf,USER_0668,IKEA,Food & Beverage,3,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06,Padang

In [88]:
# master_merchant.to_csv('master_merchant.csv', index=False)
# master_user.to_csv('master_user.csv', index=False)
# master_promo_1.to_csv('master_promo_1.csv', index=False)
master_promo_2.to_csv('master_promo_2.csv', index=False)
# transaction_dma.to_csv('transaction_dma.csv', index=False)

In [70]:
times = datetime.now().strftime('%Y-%m-%d %H:%M:%S %z')
print(times)

2024-10-25 21:40:30

In [68]:
master_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1000 non-null   object
 1   USER_ID           1000 non-null   object
 2   GENDER            1000 non-null   object
 3   RELIGION          1000 non-null   object
 4   TOTAL_ASSETS      1000 non-null   int64
 5   ACCOUNT_AGE       1000 non-null   int64
 6   TRANSACTION_TIME  1000 non-null   object
 7   SEGMENTATION      1000 non-null   object
 8   UPDATE_BY         1000 non-null   object
 9   UPDATED_TIME      1000 non-null   object
 10  CREATED_BY        1000 non-null   object
 11  CREATED_TIME      1000 non-null   object
dtypes: int64(2), object(10)
memory usage: 93.9+ KB

In [79]:
master_merchant

,ID,MCC_GROUP,MERCHANT_CATEGORY,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,ALFAMART,Food & Beverage,xKNYKdL1iVqeU7PLMJ0Se,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
1,ALFAMART,Lifestyle,Om-PC1HOUVZET2N2V_pf6,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
2,ALFAMART,Travel & Transportation,MZP2bGpIqg1ejtCNgZwgJ,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
3,ALFAMART,Gadget & Electronics,VHhEtvrM1oCyrhfDI6NlS,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
4,ALFAMART,E-Commerce,LO-pwEXEDTb_UStD6HWjz,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
...,...,...,...,...,...,...,...
83,DECATHLON,Gadget & Electronics,7rdwCy92F2rYP8rNCECob,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
84,DECATHLON,E-Commerce,UaH7Y0OPuAEYa8cWpBGDx,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
85,DECATHLON,Health & Beauty,01lh8aWVT7pFYPuRPHufU,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
86,DECATHLON,Others/Miscellaneous,JXdT6xsjO4S0CCpqVHYrP,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06
87,DECATHLON,Telco,uUsgVKdGKcn3TMcv-aV3k,Camdun,2024-10-25 21:41:06,Camdun,2024-10-25 21:41:06

In [82]:
master_promo_2

,ID,PROMO_ID,MCC_GROUP,MERCHANT_CATEGORY,RELIGION,GENDER,SEGMENTATION,PROMO_LOCATION,TOTAL_ASSETS,ACCOUNT_AGE,TRANSACTION_TIME,START_DATE,END_DATE,UPDATE_BY,UPDATED_TIME,CREATED_BY,CREATED_TIME
0,Q-n1icBaHCUX5NXlkLO00,PROMO_00000,DECATHLON,Travel & Transportation,Catholic,F,Emerging Wealth,2,4,WEEKDAY - TRAVELING TIME,24/05/25,05/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
1,BtHw4asvBBm2fOaVyUm0y,PROMO_00001,INDOMARET,Food & Beverage,Others,M,Mature High Networth,1,1,WEEKDAY - WORKING TIME,23/01/25,27/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
2,xSoS4137NHOwF2JA35Q6P,PROMO_00002,ALFAMART,Lifestyle,Islam,F,Silver Ager,4,4,WEEKEND - WEEKEND,04/03/25,27/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
3,h-9Oc_jumOAF9IWuzkGQi,PROMO_00003,IBOX,Telco,Konghucu,M,Minimal,1,5,WEEKEND - WEEKEND,18/01/25,16/09/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
4,PmArVOFg6iHLFqOVIRg_m,PROMO_00004,ERAFONE,Health & Beauty,Islam,M,Emerging Wealth,1,5,WEEKDAY - RESTING TIME,13/03/25,22/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,mnuzmq2Cts5By13t_QSY6,PROMO_09995,BARAYA,Travel & Transportation,Islam,F,Emerging Wealth,1,3,WEEKDAY - RESTING TIME,28/05/25,13/12/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9996,JlEnaRsH0mhTEKIEaYoJK,PROMO_09996,DAYTRANS,Telco,Konghucu,M,Young Gen & Early Jobber,5,5,WEEKDAY - RESTING TIME,18/12/24,29/10/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9997,kffOoC5vYDk22YddNtYrn,PROMO_09997,IKEA,Travel & Transportation,Catholic,F,All Segment,5,1,WEEKDAY - TRAVELING TIME,18/01/25,03/11/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9998,IZk0dqU0LVEAkENRT8LRX,PROMO_09998,BARAYA,E-Commerce,Catholic,F,Mature High Networth,5,3,WEEKDAY - WORKING TIME,26/01/25,13/08/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06
9999,TIWsHCrk3dqIS6pwEpWXf,PROMO_09999,DAYTRANS,Health & Beauty,Christian,M,Mature High Networth,2,4,WEEKDAY - RESTING TIME,07/05/25,17/10/25,Camdun,19:56:05,2024-10-25 21:41:06,19:56:05,2024-10-25 21:41:06

In [ ]:
python inject_promo.py transaction_dma transaction_dma.csv